/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class Layout extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    public Layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        LoadingPanel = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        categoryButton = new javax.swing.JButton();
        carsButton = new javax.swing.JButton();
        manageCustButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(153, 51, 255));
        basePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 102), null));
        basePanel.setForeground(new java.awt.Color(153, 51, 255));

        header.setBackground(new java.awt.Color(255, 102, 102));
        header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(204, 204, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Rent A Car");

        javax.swing.GroupLayout LoadingPanelLayout = new javax.swing.GroupLayout(LoadingPanel);
        LoadingPanel.setLayout(LoadingPanelLayout);
        LoadingPanelLayout.setHorizontalGroup(
            LoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        LoadingPanelLayout.setVerticalGroup(
            LoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        LoginButton.setForeground(new java.awt.Color(255, 51, 51));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        categoryButton.setForeground(new java.awt.Color(51, 255, 51));
        categoryButton.setText("Categories");
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });

        carsButton.setForeground(new java.awt.Color(51, 102, 255));
        carsButton.setText("Cars");
        carsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsButtonActionPerformed(evt);
            }
        });

        manageCustButton.setForeground(new java.awt.Color(51, 255, 255));
        manageCustButton.setText("Customer");
        manageCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustButtonActionPerformed(evt);
            }
        });

        rentalButton.setForeground(new java.awt.Color(153, 51, 255));
        rentalButton.setText("Rentals");
        rentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalButtonActionPerformed(evt);
            }
        });

        rentButton.setForeground(new java.awt.Color(255, 0, 51));
        rentButton.setText("Rent");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        returnButton.setForeground(new java.awt.Color(255, 102, 255));
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        logoutButton.setForeground(new java.awt.Color(0, 153, 153));
        logoutButton.setText("Logout");

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageCustButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginButton)
                        .addGap(18, 18, 18)
                        .addComponent(categoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(carsButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageCustButton)
                        .addGap(18, 18, 18)
                        .addComponent(rentalButton)
                        .addGap(18, 18, 18)
                        .addComponent(rentButton)
                        .addGap(18, 18, 18)
                        .addComponent(returnButton)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton)
                        .addGap(37, 37, 37))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalButtonActionPerformed
loadRentalPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_rentalButtonActionPerformed

    private void carsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsButtonActionPerformed
loadCarsPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_carsButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
loadLoginPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
loadCategoryPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void manageCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustButtonActionPerformed
loadcustomerPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_manageCustButtonActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
loadRentPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_rentButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
loadreturnPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoadingPanel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton carsButton;
    private javax.swing.JButton categoryButton;
    private javax.swing.JLabel header;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageCustButton;
    private javax.swing.JButton rentButton;
    private javax.swing.JButton rentalButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables

    private void loadLoginPanel() {
        LoadingPanel.removeAll();
        loginPanel lp =new loginPanel();
        lp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(lp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
        
    }

    private void loadCategoryPanel() {
          LoadingPanel.removeAll();
        categoryPanel cp =new categoryPanel();
        cp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(cp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }

    private void loadCarsPanel() {
        LoadingPanel.removeAll();
        carsPanel cp =new carsPanel();
        cp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(cp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }

    private void loadcustomerPanel() {
        LoadingPanel.removeAll();
        customerPanel cp =new customerPanel();
        cp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(cp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }

    private void loadRentalPanel() {
         LoadingPanel.removeAll();
        rentalPanel rp =new rentalPanel();
        rp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(rp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }

    private void loadRentPanel() {
         LoadingPanel.removeAll();
        newRentPanel rp =new newRentPanel();
        rp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(rp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }

    private void loadreturnPanel() {
         LoadingPanel.removeAll();
        returnPanel rp =new returnPanel();
        rp.setSize(LoadingPanel.getWidth(),LoadingPanel.getHeight());
        LoadingPanel.add(rp);
        LoadingPanel.repaint();
        LoadingPanel.revalidate();
    }
}
